backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "exampleSite/static/images/blog"
public_folder: "/images/blog"

collections: # A list of collections the CMS should be able to edit
  - name: "blog"
    label: "Blog Artikel"
    folder: "exampleSite/content/english/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Judul Blog", name: "title", widget: "string", default: "Judul Artikel"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Masukkan Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image", default: "images/backgrounds/page-title.jpg"}
      - {label: "Penulis", name: "author", widget: "string", default: "John Doe"}
      - {label: "Kategori", name: "kategori", widget: "string"}
      - {label: "Topik", name: "topik", widget: "list"}
      - {label: "Type", name: "post", widget: "hidden", default: "post"}
      - {label: "Gambar", name: "image", widget: "image", default: "images/blog/post-1.jpg"}
      - {label: "Deskripsi", name: "dscription", widget: "string", default: "Ini adalah deskripsi"}
      - {label: "Isi Artikel", name: "body", widget: "markdown"}
  
  