backend:
  name: git-gateway
  branch: main

local_backend: true
publish_mode: editorial_workflow
use_large_media_transforms_in_media_library: false
media_folder: "static/images"
public_folder: "/images"

collections: # A list of collections the CMS should be able to edit
  - name: "blog"
    label: "Blog Artikel"
    folder: "content/english/blog"
    create: true
    slug: "{{slug}}"
    media_folder: "/static/images/blog/"
    public_folder: "/images/blog"
    fields:
      - {label: "Judul Blog", name: "title", widget: "string", default: "Judul Artikel"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Masukkan Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image", default: "images/backgrounds/page-title.jpg"}
      - {label: "Penulis", name: "author", widget: "string", default: "John Doe"}
      - {label: "Kategori", name: "kategori", widget: "string"}
      - {label: "Topik", name: "topik", widget: "list"}
      - {label: "Type", name: "post", widget: "hidden", default: "post"}
      - {label: "Gambar", name: "image", widget: "image", default: "images/blog/post-1.jpg"}
      - {label: "Deskripsi", name: "dscription", widget: "string", default: "Ini adalah deskripsi"}
      - {label: "Isi Artikel", name: "body", widget: "markdown"}
  
  - name: "acara"
    label: "Acara"
    folder: "content/english/event"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    media_folder: "/static/images/events"
    public_folder: "images/events"
    fields:
      - {label: "Judul Acara", name: "event", widget: "string"}
      - {label: "Tanggal Di Upload", name: "publishDate", widget: "datetime"}
      - {label: "Tanggal Acara", name: "date", widget: "datetime"}
      - {label: "Masukkan Draft", name: "draft", widget: "boolean"}
      - {label: "Gambar Latar Belakang", name: "bg_image", widget: "image"}
      - {label: "Deskripsi", name: "description", widget: "string"}
      - {label: "Poster Untuk Event", name: "image", widget: "image"}
      - {label: "Harga", name: "fee", widget: "string"}
      - {label: "Link Pendaftaran", name: "apply_url", widget: "string"}
      - {label: "Tipe", name: "type", widget: "hidden", default: "event"}
      - label: "Pembicara"
        name: "speaker"
        widget: "list"
        fields: 
          - {label: "Nama Pembicara", name: "name", widget: "string"}
          - {label: "Gambar Pembicara", name: "image", widget: "string"}
          - {label: "Gelar/Penamaan", name: "designation", widget: "string"}
        
      - {label: "Body", name: "body", widget: "markdown"}