---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/staff
  label: Staff
  create: all
  match: "**/*"
- type: directory
  path: content/scholarship
  label: Scholarship
  create: all
  match: "**/*"
- type: directory
  path: content/research
  label: Research
  create: all
  match: "**/*"
- type: directory
  path: content/pasar
  label: Pasar
  create: all
  match: "**/*"
- type: directory
  path: content/notice
  label: Notice
  create: all
  match: "**/*"
- type: directory
  path: content/kkn19
  label: Kkn19
  create: all
  match: "**/*"
- type: directory
  path: content/contact
  label: Contact
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/author
  label: Author
  create: all
  match: "**/*"
- type: directory
  path: content/acara
  label: Acara
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
